apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  namespace: fiap-microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      containers:
        - name: analytics-service
          image: 654654184825.dkr.ecr.us-east-1.amazonaws.com/fiap-microservices/analytics-service:165687a
          ports:
            - containerPort: 8005
          envFrom:
            - secretRef:
                name: analytics-secret
            - secretRef:
                name: aws-credentials
          resources:
            requests:
              cpu: "100m"     # CPU mínima garantida para HPA
            limits:
              cpu: "500m"     # Máximo que o pod pode consumir
---
apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: fiap-microservices
spec:
  type: ClusterIP
  selector:
    app: analytics-service
  ports:
    - port: 8005
      targetPort: 8005
#kubectl apply -f analytics-service-deploy.yaml