apiVersion: v1
kind: Secret
metadata:
  name: evaluation-secret
  namespace: fiap-microservices
type: Opaque
stringData:
  
  PORT: "8004"
  REDIS_URL: "redis://redis-service:6379"
  FLAG_SERVICE_URL: "http://flag-service:8002"
  TARGETING_SERVICE_URL: "http://targeting-service:8003"
  SERVICE_API_KEY: "tm_key_e175a5af6c43bda02ffcad0b74f6b8b78ffbbb38af60697d2db337b8f2c1d2ea"
  # AWS data for acessing SQS
  AWS_REGION: "us-east-1"
  AWS_SQS_URL: "https://sqs.us-east-1.amazonaws.com/760729969288/evaluation-service-response-sqs"
# kubectl apply -f evaluation-secret.yaml

