apiVersion: apps/v1
kind: Deployment
metadata:
  name: evaluation-service
  namespace: fiap-microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evaluation-service
  template:
    metadata:
      labels:
        app: evaluation-service
    spec:
      containers:
        - name: evaluation-service
          image: 654654184825.dkr.ecr.us-east-1.amazonaws.com/fiap-microservices/evaluation-service:c1b2e0a
          ports:
            - containerPort: 8004
          envFrom:
            - secretRef:
                name: evaluation-secret
            - secretRef:
                name: aws-credentials
          resources:
            requests:
              cpu: "10m"     # CPU mínima garantida para HPA
            limits:
              cpu: "100m"     # Máximo que o pod pode consumir
---
apiVersion: v1
kind: Service
metadata:
  name: evaluation-service
  namespace: fiap-microservices
spec:
  type: ClusterIP
  selector:
    app: evaluation-service
  ports:
    - port: 8004
      targetPort: 8004
#kubectl apply -f evaluation-service-deploy.yaml