apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
  namespace: fiap-microservices
type: Opaque
stringData:
  DATABASE_URL: "postgresql://postgres:rootroot@auth-db.c51abplrszuc.us-east-1.rds.amazonaws.com:5432/auth_db"
  MASTER_KEY: "admin-secreto-123"
  PORT: "8001"
# kubectl apply -f auth-secret.yaml