apiVersion: v1
kind: Secret
metadata:
  name: flag-secret
  namespace: fiap-microservices
type: Opaque
stringData:
  DATABASE_URL: "postgresql://postgres:rootroot@flags-db.c51abplrszuc.us-east-1.rds.amazonaws.com:5432/flags_db"
  PORT: "8002"
  AUTH_SERVICE_URL: "http://auth-service:8001"
# kubectl apply -f flag-secret.yaml