apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: fiap-microservices
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: ASIA3CHYKEKEBAVVMI7Z
  AWS_SECRET_ACCESS_KEY: MANXfNjJ03y5K3ouKxIiKFKnTKIICoqdM6+NPA1Z
  AWS_SESSION_TOKEN: IQoJb3JpZ2luX2VjEJr//////////wEaCXVzLXdlc3QtMiJHMEUCIQDYuF08il/O0FJ8tkW7eUyFNfep5Zwp+5KBd+ZB0P9WygIgINbcZh7ZKpMZ6X79s7aYSsVHfhc/90IEViRMyc7Qm8cqtAIIYxADGgw3NjA3Mjk5NjkyODgiDI1oWRBjbV8R1RWiZCqRAie6C+UCxSM6HfUUFcFP01VmqTIVPpuaauyOIFFUr5/ltzdyWtbfWSCDgrCaztLXxlATF5zs+fU9UiRVAhGsh+RYpjsKxNN6imX8YtzDxPlV3+8BDMrY9M2GmaVMbswLGsEO+18dlX/FHTqaCxMpgYLqZdgjOIyUxGJBnxC85yH3wbe4Cz1OAa1Hd0HZtMZLwAuL5Mw8OLHGeggYAuVPXU35rh409Kyx8brKQoN9CY5COXA3Cp8EqKQtpXSdvfR977emVihomZbbEiL0nGKuV/Z/vB46js2bOxiM8SklvnS1wj5VpHQgU9kmdATCL/GJd3Mc6+qGCBAJn/153YrhLc0UhKkYmpS/aYHYVl6Rhwa7LzDfoPXKBjqdAWeh6CA5VUxqX1PM1ivr+X9Dywe+xGmzy6ZwQQsltjSDTfln6lKACM3dNA5IXsDH1nIHjBFFAw2FLWv7d/iP7QKDEQYM+nXO5qp3QhdkDS0bfxzRkVGJxbSeQmCo+bZsLmd1bqzuEljSn0reZDfnxbAyU6pNMyzj+dUzY/DtA8d3LNjcmWI/yEl8e2BLN8i8wLLhVpTsaXUU1WHaZHI=
# kubectl apply -f aws-credentials.yaml