apiVersion: apps/v1
kind: Deployment
metadata:
  name: targeting-service
  namespace: fiap-microservices

spec:
  replicas: 1

  selector:
    matchLabels:
      app: targeting-service

  template:
    metadata:
      labels:
        app: targeting-service

    spec:
      containers:
        - name: targeting-service
        
          image: 657010996850.dkr.ecr.us-east-1.amazonaws.com/fiap-microservices/targeting-service:5a85d76


          ports:
            - containerPort: 8003

          envFrom:
            - secretRef:
                name: targeting-secret

          env:
            - name: OTEL_SERVICE_NAME
              value: "targeting-service"

            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector.monitoring.svc.cluster.local:4318"

            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "http/protobuf"

            - name: OTEL_TRACES_EXPORTER
              value: "otlp"

            - name: OTEL_METRICS_EXPORTER
              value: "otlp"

            - name: SERVICE_VERSION
              value: "1.0.0"

            - name: ENVIRONMENT
              value: "fiap-lab3"

---
apiVersion: v1
kind: Service
metadata:
  name: targeting-service
  namespace: fiap-microservices

spec:
  type: ClusterIP

  selector:
    app: targeting-service

  ports:
    - port: 8003
      targetPort: 8003