apiVersion: apps/v1
kind: Deployment
metadata:
  name: targeting-service
  namespace: fiap-microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: targeting-service
  template:
    metadata:
      labels:
        app: targeting-service
    spec:
      containers:
        - name: targeting-service
          image: 654654184825.dkr.ecr.us-east-1.amazonaws.com/fiap-microservices/targeting-service:latest
          ports:
            - containerPort: 8003
          envFrom:
            - secretRef:
                name: targeting-secret
---
apiVersion: v1
kind: Service
metadata:
  name: targeting-service
  namespace: fiap-microservices
spec:
  type: ClusterIP
  selector:
    app: targeting-service
  ports:
    - port: 8003
      targetPort: 8003
#kubectl apply -f targeting-service-deploy.yaml