name: Self-Healing Auth Service

on:
  repository_dispatch:
    types: [auth-service-5xx-alert]

jobs:
  restart-auth-service:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Configure kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region us-east-1 \
            --name microservices-eks-cluster

      - name: Restart auth-service
        run: |
          kubectl rollout restart deployment/auth-service \
            -n fiap-microservices

      - name: Wait for rollout
        run: |
          kubectl rollout status deployment/auth-service \
            -n fiap-microservices